### ISSUE TITLE
Set FPS modifier on 2 different dropdown lists

### ISSUE THREAD

**Issue by guimenezessouza** [0zl/meow#26]
The Set FPS modifier is currently on both the Tools drop-down list and Options drop-down list.
![SWFpyeVagy](https://user-images.githubusercontent.com/69261617/116699470-fe83af00-a99b-11eb-965e-e212e171a304.png)
![G1MPDHGLdT](https://user-images.githubusercontent.com/69261617/116699483-017e9f80-a99c-11eb-829e-698ef0f19dc5.png)

**Comment by wispie** [comment]
next update I'll remove it
